# Generated by Django 5.0 on 2024-03-09 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabletray',
            name='id',
            field=models.CharField(blank=True, max_length=50, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='cabletray',
            name='size',
            field=models.DecimalField(choices=[(600, 600), (150, 150), (50, 50), (100, 100), (450, 450), (300, 300)], decimal_places=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='cabletray',
            name='tray_type',
            field=models.CharField(choices=[('MPT', 'MPT'), ('BST', 'BST'), ('MST', 'MST'), ('BPT', 'BPT')], max_length=3),
        ),
        migrations.AlterField(
            model_name='cabletray',
            name='unit',
            field=models.CharField(choices=[('515', '515'), ('111', '111')], default='111', max_length=50),
        ),
    ]
